export const prefixOptions = [
  "Mr",
  "Ms",
  "Dr",
  "Prof",
  "Admiral",
  "Advocate",
  "Air Chief",
  "Air Cmde",
  "Air Marshal",
  "Amb",
  "Ambassador",
  "Ar",
  "AVM",
  "Brig",
  "Captain",
  "Cdr",
  "CMA",
  "Cmde",
  "Col",
  "Commander",
];

export const countries = [
  "India",
  "Pakistan",
  "China",
  "United States",
  "United Kingdom",
  "Canada",
  "Australia",
  "Germany",
  "France",
  "Japan",
  "South Korea",
  "Singapore",
  "UAE",
  "Saudi Arabia",
  "Brazil",
  "Russia",
  "South Africa",
];

export const sectorsOfInterest = [
  "Affirmative Action",
  "Agriculture",
  "Artificial Intelligence",
  "Arts, Heritage & Culture",
  "ASCON",
  "Auto Components",
  "Automobiles",
  "Banking",
  "Bio Fuels",
  "Bioenergy",
  "Biotechnology",
  "Business Process Outsourcing",
  "Capital Goods",
  "Capital Market",
  "Chemicals",
  "Civil Aviation",
  "Climate Change",
  "Competition law",
  "Competitiveness",
  "Corporate Governance",
  "COVID-19",
  "CSR & Community Development",
];

export const functionalAreas = [
  "Academic Administration",
  "Celebrity",
  "Chairman / Managing Director / CEO",
  "CII Membership Contact",
  "Corporate Affairs",
  "Corporate Communications",
  "CSR / Sustainable Development",
  "Diplomat",
  "Doctors",
  "Engineering",
  "Export / International Trade",
  "Finance & Accounts",
  "Government",
  "Human Resource Development",
  "Information Technology",
  "Journalist",
  "Law / Judiciary",
  "Manufacturing / Production",
  "Marketing & Business Development",
  "Materials Management",
  "Media",
  "Medical",
  "Other",
  "Politicians",
  "Purchase / Procurement",
  "Quality Management",
  "Research & Development / Technology",
  "Safety / Security",
  "Top Management / COO / CTO / CFO / VPs / Directors",
  "Vendor Development",
];

export const companyTypes = [
  "Pvt Ltd",
  "Public",
  "Partnership"
];
